data:
  train_path: '../audio/sound-of-norway_old/sound-of-norway/Train/'
  eval_path: '../audio/sound-of-norway_old/sound-of-norway/Test/'
  annotations_path: '../audio/sound-of-norway_old/annotation_uncertainty.csv'
  species_list_path: './inputs/list_en_ml.csv'

parameters:
  model_weights: './inputs/checkpoints/BirdNet_49.pt'
  model_name: 'passt'
  epochs: 15
  lr: 0.001
  context: 0
  heads: 1
  weight_decay: 0.00001
  save: False